<?php

declare(strict_types=1);

/*
 * MdNotesCCGLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MdNotesCCGLib\Exceptions;

interface Exception extends \Throwable
{
}
