<?php

declare(strict_types=1);

/*
 * MdNotesCCGLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace MdNotesCCGLib;

/**
 * An interface for all configuration parameters required by the SDK.
 */
interface ConfigurationInterface
{
    public function getOAuthCredentials(): OAuthCredentials;

    /**
     * Get timeout for API calls
     */
    public function getTimeout(): int;

    /**
     * Get current API environment
     */
    public function getEnvironment(): string;

    /**
     * Get the base uri for a given server in the current environment
     *
     * @param string $server Server name
     *
     * @return string Base URI
     */
    public function getBaseUri(string $server = Server::DEFAULT_): string;
}
